In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt

In [2]:
gamma = 0.8
reward = np.array([
    [0, -10, 0, -1, -1],
    [0, 10, -1, 0, -1],
    [-1, 0, 0, 10, -1],
    [-1, 0, -10, 0, 10]
])
q_matrix = np.zeros((4,5))
transition_matrix = np.array([
    [-1, 2, -1, 1, 1],
    [-1, 3, 0, -1, 2],
    [0, -1, -1, 3, 3],
    [1, -1, 2, -1, 4]
])

valid_actions = np.array([
    [1, 3, 4],
    [1, 2, 4],
    [0, 3, 4],
    [0, 2, 4]
])

In [3]:
for i in range(1000):
    start_state = 0
    current_state = start_state
    while current_state != 3:
        action = random.choice(valid_actions[current_state])
        next_state = transition_matrix[current_state][action]
        future_rewards = []
        for action_nxt in valid_actions[next_state]:
            future_rewards.append(q_matrix[next_state][action_nxt])
        q_state = reward[current_state][action] + gamma*max(future_rewards)
        q_matrix[current_state][action] = q_state
        print(q_matrix)
        current_state = next_state
        if current_state == 3:
            print('Goal state reached')
print('Final q-matrix: ')
print(q_matrix)

[[ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  0.  0. -1.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
Goal state reached
[[ 0.  0.  0.  7.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  7.  0.]
 [ 0. 10.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  7.  0.]
 [ 0. 10.  0.  0. -1.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]]
Goal state reached
[[ 0.  0.  0.  7.  7.]
 [ 0. 10.  0.  0. -1.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.   0.   0.   7.   7. ]
 [ 0.  10.   4.6  0.  -1. ]
 [ 0.   0.   0.  10.   0. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.  -1. ]
 [ 0.   0.   0.  10.   0. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.  -1. ]
 [ 0.   0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  

 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.

 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 

 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 

 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 

 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
Goal state reached
[[ 0.  -2.   0.   7.   7. ]
 [ 0.  10.   4.6  0.   7. ]
 [ 4.6  0.   0.  10.  -1. ]
 [ 0.   0.   0.   0.   0. ]]
[[ 0.  -2.

In [1]:
"""New try"""

'New try'

In [6]:
import numpy as np
import random

In [7]:
matrix = np.array([
    [1,0,0,0,0,0],
    [0,1,1,0,0,0],
    [0,1,1,1,1,0],
    [0,0,0,1,1,0],
    [0,0,0,1,1,0],
    [0,0,0,0,9,0]
])
action_size = 4
state_size = 36

In [8]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
total_episodes = 5000
total_test_episodes = 50
max_steps = 7

learning_rate = 0.7
gamma = 0.618

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.01

In [ ]:
for episode in range(total_episodes):
    state = 0
    step = 0
    done = False
    
    for step in range(max_steps):
        exp_exp_tradeoff = random.uniform(0,1)
        
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state, :])
        else:
            action = random.randint(1,4)
        
        new_state = 
            
        qtable[state, action] = qtable[state, action] + learning_rate * (
            reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action]
        )
        state = new_state
        if done == True:
            break
    episode +=1
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)